name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      MONGO_SECURECART: ${{ secrets.MONGO_SECURECART }}  # GitHub Variable
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}  # GitHub Variable
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      SECURE_CART_KEY: ${{ secrets.SECURE_CART_KEY }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mackerlite/ecommerce:latest